//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AccountType: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_accountType {
            get {
                return ResourceManager.GetString("Label_accountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Address: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_address {
            get {
                return ResourceManager.GetString("Label_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CompanyCode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_companyCode {
            get {
                return ResourceManager.GetString("Label_companyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CompanyName: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_companyName {
            get {
                return ResourceManager.GetString("Label_companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CreditSafeCode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_creditSafeCode {
            get {
                return ResourceManager.GetString("Label_creditSafeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmailAddr: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_emailAddr {
            get {
                return ResourceManager.GetString("Label_emailAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmergencyContact1: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_emergencyContact1 {
            get {
                return ResourceManager.GetString("Label_emergencyContact1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmergencyContact2: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_emergencyContact2 {
            get {
                return ResourceManager.GetString("Label_emergencyContact2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmergencyContactPhone1: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_emergencyContactPhone1 {
            get {
                return ResourceManager.GetString("Label_emergencyContactPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EmergencyContactPhone2: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_emergencyContactPhone2 {
            get {
                return ResourceManager.GetString("Label_emergencyContactPhone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoginAccount: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_loginAccount {
            get {
                return ResourceManager.GetString("Label_loginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoginPassword: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_loginPassword {
            get {
                return ResourceManager.GetString("Label_loginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PayAccount: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_payAccount {
            get {
                return ResourceManager.GetString("Label_payAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PayPassword: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_payPassword {
            get {
                return ResourceManager.GetString("Label_payPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SafeQuestion1: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_safeQuestion1 {
            get {
                return ResourceManager.GetString("Label_safeQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SafeQuestion2: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_safeQuestion2 {
            get {
                return ResourceManager.GetString("Label_safeQuestion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SafeQuestion3: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_safeQuestion3 {
            get {
                return ResourceManager.GetString("Label_safeQuestion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SafeQuestionAnswer1: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_safeQuestionAnswer1 {
            get {
                return ResourceManager.GetString("Label_safeQuestionAnswer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SafeQuestionAnswer2: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_safeQuestionAnswer2 {
            get {
                return ResourceManager.GetString("Label_safeQuestionAnswer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SafeQuestionAnswer3: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_safeQuestionAnswer3 {
            get {
                return ResourceManager.GetString("Label_safeQuestionAnswer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShopCode: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_shopCode {
            get {
                return ResourceManager.GetString("Label_shopCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ShopName: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_shopName {
            get {
                return ResourceManager.GetString("Label_shopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telephone: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_telephone {
            get {
                return ResourceManager.GetString("Label_telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ValidDate: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_validDate {
            get {
                return ResourceManager.GetString("Label_validDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WebSite: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Label_webSite {
            get {
                return ResourceManager.GetString("Label_webSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Msg_E_0001 {
            get {
                return ResourceManager.GetString("Msg_E_0001", resourceCulture);
            }
        }
    }
}
